// ESLint flat config.
//
// `next lint` was removed in Next 16 and `next build` no longer lints, so this is invoked
// directly via `pnpm lint` and as its own CI step.

import js from '@eslint/js'
import nextPlugin from '@next/eslint-plugin-next'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'lib/payload-types.ts', // generated by the CMS, copied in by CI
      'next-env.d.ts',
      'test-results/**',
      'playwright-report/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    plugins: { '@next/next': nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
    },
  },

  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',

      // The design ships SVG logos and uses plain <img> for them deliberately (plan §6.8).
      // Keep the warning visible rather than off, so raster images are not smuggled past
      // next/image by accident.
      '@next/next/no-img-element': 'warn',
    },
  },
)
